### ISSUE TITLE
Error in Run gbc file!

### ISSUE THREAD

**Issue by questionpython** [rooby-lang/rooby#25]
$ ../Rooby -c sample-1.ro
-------------

this generate `sample-1.gbc` file!

$ ls
-------------
```
sample-1.gbc  sample-2.ro  sample-4.ro  sample-6.ro
sample-1.ro   sample-3.ro  sample-5.ro  stack.ro
```
$ ../Rooby sample-1.gbc
-------------
$ ./sample-1.gbc
-------------
```
./sample-1.gbc: line 1: syntax error near unexpected token `newline'
./sample-1.gbc: line 1: `<Def:set>'
```
why not run compiled file?

**Comment by st0012** [comment]
Hello, it's because I haven't finish that part when you tried it 😅, sorry about that.
But I just fixed it now, and changed compiled file's extension from `gbc` to `rbc` (means `Rooby Bytecode)
And since the `rbc` files is just some vm instructions, you still need Rooby vm to execute them. 

Here's the full usage instructions :

**Execute Rooby file using VM**

(might see errors on sample-6 since vm hasn't support block yet)
``` 
$ rooby ./samples/sample-1.ro
#=> 16
```

**Execute Rooby file without vm, using the evaluator package (will be once vm is mature enough)**

```
$ rooby --without-vm ./samples/sample-1.ro
#=> 16
```

**Compile Rooby code**

```
$ rooby -c ./samples/sample-1.ro
```

You'll see `sample-1.rbc` in `./samples`

**Execute bytecode**

```
$ rooby ./samples/sample-1.rbc
```

**Comment by st0012** [comment]
@questionpython I'm going to close this issue, but you can reopen it if you meet this problem again.
